spring.application.name=stockex
spring.datasource.url=jdbc:oracle:thin:@//10.0.0.25:1521/xepdb1
spring.datasource.username=system
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true